### ISSUE TITLE
Quadkey -> geometry

### ISSUE THREAD

**Issue by lukasugar** [muety/pyquadkey2#12]
Is there a way to get geometry (WKT or GeoJSON) of a quadkey?

**Comment by amdouglas** [comment]
from shapely.geometry import box

def __generate_qk_geom(self, qk):
        minx, miny = qk.to_geo(quadkey.TileAnchor.ANCHOR_SW)
        maxx, maxy = qk.to_geo(quadkey.TileAnchor.ANCHOR_NE)
        return box(miny, minx, maxy, maxx)
