### ISSUE TITLE
Error in the implementation of tile box boundaries

### ISSUE THREAD

**Issue by ysig** [muety/pyquadkey2#13]
Hi,

thank you for this really useful library.

I noticed an unexpected behavior, when I run:
```
from pyquadkey2 import quadkey
def in_boundaries(lat, lon, res):
    qk = quadkey.from_geo((lat, lon), res)
    min_lat, min_lon = qk.to_geo(quadkey.TileAnchor.ANCHOR_SW)
    max_lat, max_lon = qk.to_geo(quadkey.TileAnchor.ANCHOR_NE)
    assert min_lat <= lat <= max_lat                   # error
```

for 

```
in_boundaries(-27.052395, 152.97702, 6)
```

I get an assertion returns AssertionError is being raised, which is a behavior that clearly shouldn't happen as each point should be included in its associated rectangular box (or I'm missing something).

Thank you,

**Comment by ymorin-orange** [comment]
> `assert min_lat <= lat <= max_lat`

This looks fishy. One of the comaprison will return `True`, and that will be compared
to the last element.

I.e. if you add parentheses, it is the same as `(min_lat <= lat) <= max_lat`, which
would be evaluated as `True <= max_lat`, which then can't evaluate to `True`.

Have you tried printing the three values, and splitting the assert in two?

**Comment by muety** [comment]
Sorry, didn't receive any e-mail notifications on this repo in the past time and thus totally missed all recent issues. Will have a look into this later today!

**Comment by muety** [comment]
Looks like we're indeed picking up the wrong tile here. Your code yields quadkey `311213`, while testing with  [jquad](https://github.com/ethlo/jquad) returns `311211` (one tile below). Perhaps a floating point precision / rounding issue? Definitely something we'll need to look into! Thanks for bringing this up!

**Comment by muety** [comment]
This is what it looks like on the map: blue (1) is your query point, green (2 and 3) are SW and NE reported by pyquadkey2 and red (4 and 5) are SW and NE reported by jquad (which are probably the correct ones).

![image](https://github.com/muety/pyquadkey2/assets/8978843/d74f5f57-9088-4a53-a552-1cf022e19afd)

```
fid,lat,lon,color
1,-27.052395,152.97702,1
2,-31.952162238025,151.875,2
3,-27.059125784374,157.5,2
4,-27.05912578437406,151.875,3
5,-21.94304553343818,157.5,3
```

**Comment by muety** [comment]
Actually, the key returned by `pyquadkey2` is correct, at least Microsoft's reference implementation yields the same result:

```csharp
using Microsoft.MapPoint;

double latitude = -27.052395;
double longitude = 152.97702;
int levelOfDetail = 6;

string quadKey = GetQuadKey(latitude, longitude, levelOfDetail);

Console.WriteLine("QuadKey: " + quadKey);  // returns '311213'

static string GetQuadKey(double latitude, double longitude, int levelOfDetail)
{
    int pixelX, pixelY;
    TileSystem.LatLongToPixelXY(latitude, longitude, levelOfDetail, out pixelX, out pixelY);

    int tileX, tileY;
    TileSystem.PixelXYToTileXY(pixelX, pixelY, out tileX, out tileY);

    return TileSystem.TileXYToQuadKey(tileX, tileY, levelOfDetail);
}
```

But this would mean both [ethlo/jquad](https://github.com/ethlo/jquad) and [CartoDB/python-quadkey](https://github.com/CartoDB/python-quadkey) are wrong? :thinking: 

So, the bug must be somewhere in the tile -> bbox calculation part.

**Comment by muety** [comment]
I went through every line of the code, but couldn't find the issue. I honestly have no clue what's wrong here. Would love to get some help on this!

**Comment by muety** [comment]
Thanks a lot for your help on this!
