### ISSUE TITLE
[Bug] no valid_geo as a precondition in QuadKey class

### ISSUE THREAD

**Issue by CoreJa** [muety/pyquadkey2#19]
```python
from pyquadkey2.quadkey import QuadKey
QuadKey.from_geo((90,180),3) #?
Out[3]: 111

QuadKey.from_geo((91,180),3) #???
Out[4]: 111

QuadKey.from_geo((999,180),3)
Out[5]: 111

QuadKey.from_geo((999,999),3) #??????
Out[6]: 111

from pyquadkey2 import quadkey
quadkey.from_geo((90,180),3) # this might be expected, but the given exception without any explaination is way too wild

Traceback (most recent call last):
  File "/Users/ruic/Projects/venv_3.10/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-f73f676a55f9>", line 1, in <module>
    quadkey.from_geo((90,180),3)
  File "/Users/ruic/Projects/venv_3.10/lib/python3.10/site-packages/pyquadkey2/quadkey/util.py", line 9, in wrapper
    assert precondition(*args, **kwargs)
AssertionError
```
I have tested it on [what the tile](https://labs.mapbox.com/what-the-tile/), it allows (90,180) as a input. 

I personally think the geo limit is okay. The geo does exists, it just does not belong to any tiles anymore.(So maybe a specific tile __unknown__?) Or just forbid any one to use that as a input. Anyway it should be consistent. Any maybe we can have a user-friendly warning or exception as a reminder instead of Assert.

And one more thing, there is no way to tell whether your `geo` is (lat,lon) or (lon,lat), unless you read the code, which is also not user-friendly, might consider fix it while you fix the above.

**Comment by muety** [comment]
To Do:
* [ ] Move validity checks into class methods (and get rid of decorator)
* [ ] Improve error messages
