### ISSUE TITLE
pip install pyquadkey2  is errored for windows 10 

### ISSUE THREAD

**Issue by robertwang2015** [muety/pyquadkey2#2]
$ pip install pyquadkey2
Collecting pyquadkey2
  Using cached https://files.pythonhosted.org/packages/f2/5e/671b87ea0da1066e5b65ab32ef7efb6ca5f8d0ce894e5dc3a60dc53f4c13/pyquadkey2-0.2
.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\reiho.oh\appdata\local\programs\python\python37\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\reiho.oh\\AppData\\Local\\Temp\\pip-install-nvofsb3r\\pyquadkey2\\setup.py'"'"'; __file__='"'"'C:\\Users\\reiho.oh\\AppD
ata\\Local\\Temp\\pip-install-nvofsb3r\\pyquadkey2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().repl
ace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\reiho.oh\AppData\Local\Temp\pip-install-nvofsb3r\pyquadkey2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\reiho.oh\AppData\Local\Temp\pip-install-nvofsb3r\pyquadkey2\setup.py", line 11, in <module>
        long_description = fh.read()
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x85 in position 1026: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by muety** [comment]
Resolved with #3
