### ISSUE TITLE
center should be half size

### ISSUE THREAD

**Issue by g-chi** [muety/pyquadkey2#6]
ANCHOR_CENTER is exactly same as ANCHOR_SE in the current version. Should it be `+ 128` rather than `+ 256`?
https://github.com/muety/pyquadkey2/blob/12e44a46f2ee6a8ce9c68b51e9c4e10408116943/src/pyquadkey2/quadkey/tilesystem/tilesystem.pyx#L73

**Comment by Kodiologist** [comment]
Yeah, this is a heck of a bug. It's a shame that this repository was forked from the original specifically because it was unmaintained, and now this one has also gone unmaintained. C'est la vie.

**Comment by muety** [comment]
> It's a shame that this repository was forked from the original specifically because it was unmaintained, and now this one has also gone unmaintained. C'est la vie.

Contributions are always welcome...
